<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="AutoMapper"
                          Version="13.0.1" />
        <PackageReference Include="FluentValidation"
                          Version="11.11.0" />
        <PackageReference Include="FluentValidation.AspNetCore"
                          Version="11.3.0" />
        <PackageReference Include="Microsoft.Extensions.Logging"
                          Version="8.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"
                          Version="8.0.8" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens"
                          Version="8.0.2" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt"
                          Version="8.0.2" />
        <PackageReference Include="KeyedSemaphores"
                          Version="5.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore"
                          Version="8.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"
                          Version="8.0.8" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Configuration\Authentication\" />
        <Folder Include="Validations\" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../BaseReservation.Common/BaseReservation.Common.csproj" />
        <ProjectReference Include="../BaseReservation.Domain/BaseReservation.Domain.csproj" />
        <ProjectReference Include="..\BaseReservation.Utils\BaseReservation.Utils.csproj" />
    </ItemGroup>
</Project>