// <auto-generated />
using System;
using BaseReservation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseReservation.Infrastructure.Migrations
{
    [DbContext(typeof(BaseReservationContext))]
    partial class BaseReservationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Canton", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<byte>("IdProvincia")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdProvincia" }, "IX_Canton_IdProvincia");

                    b.ToTable("Canton");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Categorium", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Cliente", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionExacta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<short>("IdDistrito")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasDefaultValue("");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdDistrito" }, "IX_Cliente_IdDistrito");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Contacto", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("IdProveedor")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdProveedor" }, "IX_Contacto_IdProveedor");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetalleFactura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.Property<long>("IdFactura")
                        .HasColumnType("bigint");

                    b.Property<short?>("IdProducto")
                        .HasColumnType("smallint");

                    b.Property<byte?>("IdServicio")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MontoImpuesto")
                        .HasColumnType("money");

                    b.Property<decimal>("MontoSubtotal")
                        .HasColumnType("money");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("money");

                    b.Property<byte>("NumeroLinea")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TarifaServicio")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdFactura" }, "IX_DetalleFactura_IdFactura");

                    b.HasIndex(new[] { "IdServicio" }, "IX_DetalleFactura_IdServicio");

                    b.ToTable("DetalleFactura");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetalleFacturaProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<long>("IdDetalleFactura")
                        .HasColumnType("bigint");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdDetalleFactura" }, "IX_DetalleFacturaProducto_IdDetalleFactura");

                    b.HasIndex(new[] { "IdProducto" }, "IX_DetalleFacturaProducto_IdProducto");

                    b.ToTable("DetalleFacturaProducto");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetallePedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<short?>("IdProducto")
                        .HasColumnType("smallint");

                    b.Property<byte?>("IdServicio")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MontoImpuesto")
                        .HasColumnType("money");

                    b.Property<decimal>("MontoSubtotal")
                        .HasColumnType("money");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("money");

                    b.Property<byte>("NumeroLinea")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TarifaServicio")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdPedido" }, "IX_DetallePedido_IdPedido");

                    b.HasIndex(new[] { "IdServicio" }, "IX_DetallePedido_IdServicio");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetallePedidoProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<long>("IdDetallePedido")
                        .HasColumnType("bigint");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdDetallePedido" }, "IX_DetallePedidoProducto_IdDetallePedido");

                    b.HasIndex(new[] { "IdProducto" }, "IX_DetallePedidoProducto_IdProducto");

                    b.ToTable("DetallePedidoProducto");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetalleReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("IdProducto")
                        .HasColumnType("smallint");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<byte?>("IdServicio")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdReserva" }, "IX_ReservaServicio_IdReserva");

                    b.HasIndex(new[] { "IdServicio" }, "IX_ReservaServicio_IdServicio");

                    b.ToTable("DetalleReserva");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Distrito", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<byte>("IdCanton")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdCanton" }, "IX_Distrito_IdCanton");

                    b.ToTable("Distrito");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.EstadoPedido", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("EstadoPedido");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Factura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Consecutivo")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<short>("IdCliente")
                        .HasColumnType("smallint");

                    b.Property<byte>("IdImpuesto")
                        .HasColumnType("tinyint");

                    b.Property<long?>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<byte>("IdSucursal")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdTipoPago")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MontoImpuesto")
                        .HasColumnType("money");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("money");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdCliente" }, "IX_Factura_IdCliente");

                    b.HasIndex(new[] { "IdImpuesto" }, "IX_Factura_IdImpuesto");

                    b.HasIndex(new[] { "IdPedido" }, "IX_Factura_IdPedido");

                    b.HasIndex(new[] { "IdSucursal" }, "IX_Factura_IdSucursal");

                    b.HasIndex(new[] { "IdTipoPago" }, "IX_Factura_IdTipoPago");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Feriado", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("Dia")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Feriado");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Genero", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Horario", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Impuesto", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.ToTable("Impuesto");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Inventario", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("IdSucursal")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("TipoInventario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdSucursal" }, "IX_Inventario_IdSucursal");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.InventarioProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Disponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<short>("IdInventario")
                        .HasColumnType("smallint");

                    b.Property<short>("IdProducto")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Maxima")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Minima")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdInventario" }, "IX_InventarioProducto_IdInventario");

                    b.HasIndex(new[] { "IdProducto" }, "IX_InventarioProducto_IdProducto");

                    b.ToTable("InventarioProducto");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.InventarioProductoMovimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<long>("IdInventarioProducto")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdInventarioProducto" }, "IX_InventarioProductoMovimiento_IdInventarioProducto");

                    b.ToTable("InventarioProductoMovimiento");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Consecutivo")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<short>("IdCliente")
                        .HasColumnType("smallint");

                    b.Property<byte>("IdEstadoPedido")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdImpuesto")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<byte>("IdSucursal")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdTipoPago")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MontoImpuesto")
                        .HasColumnType("money");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("money");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoPedido");

                    b.HasIndex(new[] { "IdCliente" }, "IX_Pedido_IdCliente");

                    b.HasIndex(new[] { "IdImpuesto" }, "IX_Pedido_IdImpuesto");

                    b.HasIndex(new[] { "IdReserva" }, "IX_Pedido_IdReserva");

                    b.HasIndex(new[] { "IdSucursal" }, "IX_Pedido_IdSucursal");

                    b.HasIndex(new[] { "IdTipoPago" }, "IX_Pedido_IdTipoPago");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Producto", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Costo")
                        .HasColumnType("money");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("IdCategoria")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdUnidadMedida")
                        .HasColumnType("tinyint");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdCategoria" }, "IX_Producto_IdCategoria");

                    b.HasIndex(new[] { "IdUnidadMedida" }, "IX_Producto_IdUnidadMedida");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Proveedor", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CedulaJuridica")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionExacta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<short>("IdDistrito")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RasonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdDistrito" }, "IX_Proveedor_IdDistrito");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Provincium", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("P")
                        .IsFixedLength();

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<short>("IdCliente")
                        .HasColumnType("smallint");

                    b.Property<byte>("IdSucursal")
                        .HasColumnType("tinyint");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdCliente" }, "IX_Reserva_IdCliente");

                    b.HasIndex(new[] { "IdSucursal" }, "IX_Reserva_IdSucursal");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.ReservaPreguntum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Respuesta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdReserva" }, "IX_ReservaPregunta_IdReserva");

                    b.ToTable("ReservaPregunta");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Rol", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Servicio", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("IdTipoServicio")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("money");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdTipoServicio" }, "IX_Servicio_IdTipoServicio");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Sucursal", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionExacta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<short>("IdDistrito")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdDistrito" }, "IX_Sucursal_IdDistrito");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.SucursalFeriado", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short>("Anno")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<byte>("IdFeriado")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdSucursal")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdFeriado" }, "IX_SucursalFeriado_IdFeriado");

                    b.HasIndex(new[] { "IdSucursal" }, "IX_SucursalFeriado_IdSucursal");

                    b.ToTable("SucursalFeriado");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.SucursalHorario", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short>("IdHorario")
                        .HasColumnType("smallint");

                    b.Property<byte>("IdSucursal")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdHorario" }, "IX_SucursalHorario_IdHorario");

                    b.HasIndex(new[] { "IdSucursal" }, "IX_SucursalHorario_IdSucursal");

                    b.ToTable("SucursalHorario");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.SucursalHorarioBloqueo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<short>("IdSucursalHorario")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdSucursalHorario" }, "IX_SucursalHorarioBloqueo_IdSucursalHorario");

                    b.ToTable("SucursalHorarioBloqueo");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.TipoPago", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Referencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoPago");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.TipoServicio", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<TimeOnly>("Duracion")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoServicio");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.TokenMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime");

                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_TokenMaster_IdUsuario");

                    b.ToTable("TokenMaster");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.UnidadMedidum", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("UnidadMedida");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Usuario", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contrasenna")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionExacta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<short>("IdDistrito")
                        .HasColumnType("smallint");

                    b.Property<byte>("IdGenero")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdDistrito" }, "IX_Usuario_IdDistrito");

                    b.HasIndex(new[] { "IdGenero" }, "IX_Usuario_IdGenero");

                    b.HasIndex(new[] { "IdRol" }, "IX_Usuario_IdRol");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.UsuarioSucursal", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<byte>("IdSucursal")
                        .HasColumnType("tinyint");

                    b.Property<short>("IdUsuario")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdSucursal" }, "IX_UsuarioSucursal_IdSucursal");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_UsuarioSucursal_IdUsuario");

                    b.ToTable("UsuarioSucursal");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Canton", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Provincium", "IdProvinciaNavigation")
                        .WithMany("Cantons")
                        .HasForeignKey("IdProvincia")
                        .IsRequired()
                        .HasConstraintName("FK_Canton_Provincia");

                    b.Navigation("IdProvinciaNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Cliente", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Distrito", "IdDistritoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdDistrito")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_Distrito");

                    b.Navigation("IdDistritoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Contacto", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Contactos")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Contacto_Proveedor");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetalleFactura", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Factura", "IdFacturaNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdFactura")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleFactura_Factura");

                    b.HasOne("BaseReservation.Infrastructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK_DetalleFactura_Producto");

                    b.HasOne("BaseReservation.Infrastructure.Models.Servicio", "IdServicioNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK_DetalleFactura_Servicio");

                    b.Navigation("IdFacturaNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetalleFacturaProducto", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.DetalleFactura", "IdDetalleFacturaNavigation")
                        .WithMany("DetalleFacturaProductos")
                        .HasForeignKey("IdDetalleFactura")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleFacturaProducto_DetalleFactura");

                    b.HasOne("BaseReservation.Infrastructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleFacturaProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleFacturaProducto_Producto");

                    b.Navigation("IdDetalleFacturaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetallePedido", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK_DetallePedido_Pedido");

                    b.HasOne("BaseReservation.Infrastructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK_DetallePedido_Producto");

                    b.HasOne("BaseReservation.Infrastructure.Models.Servicio", "IdServicioNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK_DetallePedido_Servicio");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetallePedidoProducto", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.DetallePedido", "IdDetallePedidoNavigation")
                        .WithMany("DetallePedidoProductos")
                        .HasForeignKey("IdDetallePedido")
                        .IsRequired()
                        .HasConstraintName("FK_DetallePedidoProducto_DetallePedido");

                    b.HasOne("BaseReservation.Infrastructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetallePedidoProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_DetallePedidoProducto_Producto");

                    b.Navigation("IdDetallePedidoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetalleReserva", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleReservas")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK_DetalleReserva_Producto");

                    b.HasOne("BaseReservation.Infrastructure.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleReservas")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleReserva_Reserva");

                    b.HasOne("BaseReservation.Infrastructure.Models.Servicio", "IdServicioNavigation")
                        .WithMany("DetalleReservas")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK_DetalleReserva_Servicio");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Distrito", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Canton", "IdCantonNavigation")
                        .WithMany("Distritos")
                        .HasForeignKey("IdCanton")
                        .IsRequired()
                        .HasConstraintName("FK_Distrito_Canton");

                    b.Navigation("IdCantonNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Factura", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Cliente");

                    b.HasOne("BaseReservation.Infrastructure.Models.Impuesto", "IdImpuestoNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdImpuesto")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Impuesto");

                    b.HasOne("BaseReservation.Infrastructure.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("FK_Factura_Pedido");

                    b.HasOne("BaseReservation.Infrastructure.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Sucursal");

                    b.HasOne("BaseReservation.Infrastructure.Models.TipoPago", "IdTipoPagoNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdTipoPago")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_TipoPago");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdImpuestoNavigation");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdSucursalNavigation");

                    b.Navigation("IdTipoPagoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Inventario", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Sucursal");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.InventarioProducto", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Inventario", "IdInventarioNavigation")
                        .WithMany("InventarioProductos")
                        .HasForeignKey("IdInventario")
                        .IsRequired()
                        .HasConstraintName("FK_InventarioProducto_Inventario");

                    b.HasOne("BaseReservation.Infrastructure.Models.Producto", "IdProductoNavigation")
                        .WithMany("InventarioProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_InventarioProducto_Producto");

                    b.Navigation("IdInventarioNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.InventarioProductoMovimiento", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.InventarioProducto", "IdInventarioProductoNavigation")
                        .WithMany("InventarioProductoMovimientos")
                        .HasForeignKey("IdInventarioProducto")
                        .IsRequired()
                        .HasConstraintName("FK_InventarioProductoMovimiento_InventarioProducto");

                    b.Navigation("IdInventarioProductoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Pedido", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Cliente");

                    b.HasOne("BaseReservation.Infrastructure.Models.EstadoPedido", "IdEstadoPedidoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdEstadoPedido")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_EstadoPedido");

                    b.HasOne("BaseReservation.Infrastructure.Models.Impuesto", "IdImpuestoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdImpuesto")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Impuesto");

                    b.HasOne("BaseReservation.Infrastructure.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Reserva");

                    b.HasOne("BaseReservation.Infrastructure.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Sucursal");

                    b.HasOne("BaseReservation.Infrastructure.Models.TipoPago", "IdTipoPagoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdTipoPago")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_TipoPago");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoPedidoNavigation");

                    b.Navigation("IdImpuestoNavigation");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdSucursalNavigation");

                    b.Navigation("IdTipoPagoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Producto", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Categoria");

                    b.HasOne("BaseReservation.Infrastructure.Models.UnidadMedidum", "IdUnidadMedidaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdUnidadMedida")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_UnidadMedida");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUnidadMedidaNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Proveedor", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Distrito", "IdDistritoNavigation")
                        .WithMany("Proveedors")
                        .HasForeignKey("IdDistrito")
                        .IsRequired()
                        .HasConstraintName("FK_Proveedor_Distrito");

                    b.Navigation("IdDistritoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Reserva", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Reserva_Cliente");

                    b.HasOne("BaseReservation.Infrastructure.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_Reserva_Sucursal");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.ReservaPreguntum", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Reserva", "IdReservaNavigation")
                        .WithMany("ReservaPregunta")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK_ReservaPregunta_Reserva");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Servicio", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.TipoServicio", "IdTipoServicioNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdTipoServicio")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_TipoServicio");

                    b.Navigation("IdTipoServicioNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Sucursal", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Distrito", "IdDistritoNavigation")
                        .WithMany("Sucursals")
                        .HasForeignKey("IdDistrito")
                        .IsRequired()
                        .HasConstraintName("FK_Sucursal_Distrito");

                    b.Navigation("IdDistritoNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.SucursalFeriado", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Feriado", "IdFeriadoNavigation")
                        .WithMany("SucursalFeriados")
                        .HasForeignKey("IdFeriado")
                        .IsRequired()
                        .HasConstraintName("FK_SucursalFeriado_Feriado");

                    b.HasOne("BaseReservation.Infrastructure.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("SucursalFeriados")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_SucursalFeriado_Sucursal");

                    b.Navigation("IdFeriadoNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.SucursalHorario", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Horario", "IdHorarioNavigation")
                        .WithMany("SucursalHorarios")
                        .HasForeignKey("IdHorario")
                        .IsRequired()
                        .HasConstraintName("FK_SucursalHorario_Horario");

                    b.HasOne("BaseReservation.Infrastructure.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("SucursalHorarios")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_SucursalHorario_Sucursal");

                    b.Navigation("IdHorarioNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.SucursalHorarioBloqueo", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.SucursalHorario", "IdSucursalHorarioNavigation")
                        .WithMany("SucursalHorarioBloqueos")
                        .HasForeignKey("IdSucursalHorario")
                        .IsRequired()
                        .HasConstraintName("FK_SucursalHorarioBloqueo_SucursalHorario");

                    b.Navigation("IdSucursalHorarioNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.TokenMaster", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("TokenMasters")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_TokenMaster_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Usuario", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Distrito", "IdDistritoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdDistrito")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Distrito");

                    b.HasOne("BaseReservation.Infrastructure.Models.Genero", "IdGeneroNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdGenero")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Genero");

                    b.HasOne("BaseReservation.Infrastructure.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("IdDistritoNavigation");

                    b.Navigation("IdGeneroNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.UsuarioSucursal", b =>
                {
                    b.HasOne("BaseReservation.Infrastructure.Models.Sucursal", "IdSucursalNavigation")
                        .WithMany("UsuarioSucursals")
                        .HasForeignKey("IdSucursal")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioSucursal_Sucursal");

                    b.HasOne("BaseReservation.Infrastructure.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioSucursals")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioSucursal_Usuario");

                    b.Navigation("IdSucursalNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Canton", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Pedidos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetalleFactura", b =>
                {
                    b.Navigation("DetalleFacturaProductos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.DetallePedido", b =>
                {
                    b.Navigation("DetallePedidoProductos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Distrito", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Proveedors");

                    b.Navigation("Sucursals");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Feriado", b =>
                {
                    b.Navigation("SucursalFeriados");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Genero", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Horario", b =>
                {
                    b.Navigation("SucursalHorarios");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Impuesto", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Inventario", b =>
                {
                    b.Navigation("InventarioProductos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.InventarioProducto", b =>
                {
                    b.Navigation("InventarioProductoMovimientos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Producto", b =>
                {
                    b.Navigation("DetalleFacturaProductos");

                    b.Navigation("DetalleFacturas");

                    b.Navigation("DetallePedidoProductos");

                    b.Navigation("DetallePedidos");

                    b.Navigation("DetalleReservas");

                    b.Navigation("InventarioProductos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Proveedor", b =>
                {
                    b.Navigation("Contactos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Provincium", b =>
                {
                    b.Navigation("Cantons");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Reserva", b =>
                {
                    b.Navigation("DetalleReservas");

                    b.Navigation("Pedidos");

                    b.Navigation("ReservaPregunta");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Servicio", b =>
                {
                    b.Navigation("DetalleFacturas");

                    b.Navigation("DetallePedidos");

                    b.Navigation("DetalleReservas");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Sucursal", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Inventarios");

                    b.Navigation("Pedidos");

                    b.Navigation("Reservas");

                    b.Navigation("SucursalFeriados");

                    b.Navigation("SucursalHorarios");

                    b.Navigation("UsuarioSucursals");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.SucursalHorario", b =>
                {
                    b.Navigation("SucursalHorarioBloqueos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.TipoPago", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.TipoServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.UnidadMedidum", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BaseReservation.Infrastructure.Models.Usuario", b =>
                {
                    b.Navigation("TokenMasters");

                    b.Navigation("UsuarioSucursals");
                });
#pragma warning restore 612, 618
        }
    }
}
